// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Uploader.Infrastructure.Data;
using Uploader.Infrastructure.Data.Models;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(AppDbContext), typeof(AppDbContextModel))]
