// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Update.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Uploader.Infrastructure.Data.Models
{
    public partial class AppDbContextModel
    {
        private AppDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("b5efe544-9a75-40e6-8c9f-ab0e6fc808a4"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var upload = UploadEntityType.Create(this);

            UploadEntityType.CreateAnnotations(upload);

            AddAnnotation("ProductVersion", "10.0.9");
            AddRuntimeAnnotation("Relational:RelationalModelFactory", () => CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var upload = FindEntityType("Uploader.Core.Entities.Upload")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            upload.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var uploaderCoreEntitiesUploadTableBase = new TableBase("Uploader.Core.Entities.Upload", null, relationalModel);
            var checksumMd5ColumnBase = new ColumnBase<ColumnMappingBase>("ChecksumMd5", "TEXT", uploaderCoreEntitiesUploadTableBase);
            uploaderCoreEntitiesUploadTableBase.Columns.Add("ChecksumMd5", checksumMd5ColumnBase);
            var contentTypeColumnBase = new ColumnBase<ColumnMappingBase>("ContentType", "TEXT", uploaderCoreEntitiesUploadTableBase)
            {
                IsNullable = true
            };
            uploaderCoreEntitiesUploadTableBase.Columns.Add("ContentType", contentTypeColumnBase);
            var extensionColumnBase = new ColumnBase<ColumnMappingBase>("Extension", "TEXT", uploaderCoreEntitiesUploadTableBase)
            {
                IsNullable = true
            };
            uploaderCoreEntitiesUploadTableBase.Columns.Add("Extension", extensionColumnBase);
            var fileIdColumnBase = new ColumnBase<ColumnMappingBase>("FileId", "TEXT", uploaderCoreEntitiesUploadTableBase);
            uploaderCoreEntitiesUploadTableBase.Columns.Add("FileId", fileIdColumnBase);
            var idColumnBase = new ColumnBase<ColumnMappingBase>("Id", "INTEGER", uploaderCoreEntitiesUploadTableBase);
            uploaderCoreEntitiesUploadTableBase.Columns.Add("Id", idColumnBase);
            var isDeletedColumnBase = new ColumnBase<ColumnMappingBase>("IsDeleted", "INTEGER", uploaderCoreEntitiesUploadTableBase);
            uploaderCoreEntitiesUploadTableBase.Columns.Add("IsDeleted", isDeletedColumnBase);
            var keyColumnBase = new ColumnBase<ColumnMappingBase>("Key", "TEXT", uploaderCoreEntitiesUploadTableBase);
            uploaderCoreEntitiesUploadTableBase.Columns.Add("Key", keyColumnBase);
            var originalFilenameColumnBase = new ColumnBase<ColumnMappingBase>("OriginalFilename", "TEXT", uploaderCoreEntitiesUploadTableBase);
            uploaderCoreEntitiesUploadTableBase.Columns.Add("OriginalFilename", originalFilenameColumnBase);
            var remoteIpAddressColumnBase = new ColumnBase<ColumnMappingBase>("RemoteIpAddress", "TEXT", uploaderCoreEntitiesUploadTableBase)
            {
                IsNullable = true
            };
            uploaderCoreEntitiesUploadTableBase.Columns.Add("RemoteIpAddress", remoteIpAddressColumnBase);
            var sizeColumnBase = new ColumnBase<ColumnMappingBase>("Size", "INTEGER", uploaderCoreEntitiesUploadTableBase);
            uploaderCoreEntitiesUploadTableBase.Columns.Add("Size", sizeColumnBase);
            var uploadTimeColumnBase = new ColumnBase<ColumnMappingBase>("UploadTime", "TEXT", uploaderCoreEntitiesUploadTableBase);
            uploaderCoreEntitiesUploadTableBase.Columns.Add("UploadTime", uploadTimeColumnBase);
            var userAgentColumnBase = new ColumnBase<ColumnMappingBase>("UserAgent", "TEXT", uploaderCoreEntitiesUploadTableBase)
            {
                IsNullable = true
            };
            uploaderCoreEntitiesUploadTableBase.Columns.Add("UserAgent", userAgentColumnBase);
            relationalModel.DefaultTables.Add("Uploader.Core.Entities.Upload", uploaderCoreEntitiesUploadTableBase);
            var uploaderCoreEntitiesUploadMappingBase = new TableMappingBase<ColumnMappingBase>(upload, uploaderCoreEntitiesUploadTableBase, null);
            uploaderCoreEntitiesUploadTableBase.AddTypeMapping(uploaderCoreEntitiesUploadMappingBase, false);
            defaultTableMappings.Add(uploaderCoreEntitiesUploadMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase, upload.FindProperty("Id")!, uploaderCoreEntitiesUploadMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)checksumMd5ColumnBase, upload.FindProperty("ChecksumMd5")!, uploaderCoreEntitiesUploadMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)contentTypeColumnBase, upload.FindProperty("ContentType")!, uploaderCoreEntitiesUploadMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)extensionColumnBase, upload.FindProperty("Extension")!, uploaderCoreEntitiesUploadMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)fileIdColumnBase, upload.FindProperty("FileId")!, uploaderCoreEntitiesUploadMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)isDeletedColumnBase, upload.FindProperty("IsDeleted")!, uploaderCoreEntitiesUploadMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)keyColumnBase, upload.FindProperty("Key")!, uploaderCoreEntitiesUploadMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)originalFilenameColumnBase, upload.FindProperty("OriginalFilename")!, uploaderCoreEntitiesUploadMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)remoteIpAddressColumnBase, upload.FindProperty("RemoteIpAddress")!, uploaderCoreEntitiesUploadMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)sizeColumnBase, upload.FindProperty("Size")!, uploaderCoreEntitiesUploadMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)uploadTimeColumnBase, upload.FindProperty("UploadTime")!, uploaderCoreEntitiesUploadMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)userAgentColumnBase, upload.FindProperty("UserAgent")!, uploaderCoreEntitiesUploadMappingBase);

            var tableMappings = new List<TableMapping>();
            upload.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var uploadsTable = new Table("Uploads", null, relationalModel);
            var idColumn = new Column("Id", "INTEGER", uploadsTable);
            uploadsTable.Columns.Add("Id", idColumn);
            idColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<long>(idColumn);
            var checksumMd5Column = new Column("ChecksumMd5", "TEXT", uploadsTable);
            uploadsTable.Columns.Add("ChecksumMd5", checksumMd5Column);
            checksumMd5Column.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(checksumMd5Column);
            var contentTypeColumn = new Column("ContentType", "TEXT", uploadsTable)
            {
                IsNullable = true
            };
            uploadsTable.Columns.Add("ContentType", contentTypeColumn);
            contentTypeColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(contentTypeColumn);
            var extensionColumn = new Column("Extension", "TEXT", uploadsTable)
            {
                IsNullable = true
            };
            uploadsTable.Columns.Add("Extension", extensionColumn);
            extensionColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(extensionColumn);
            var fileIdColumn = new Column("FileId", "TEXT", uploadsTable);
            uploadsTable.Columns.Add("FileId", fileIdColumn);
            fileIdColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(fileIdColumn);
            var isDeletedColumn = new Column("IsDeleted", "INTEGER", uploadsTable);
            uploadsTable.Columns.Add("IsDeleted", isDeletedColumn);
            isDeletedColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<bool>(isDeletedColumn);
            var keyColumn = new Column("Key", "TEXT", uploadsTable);
            uploadsTable.Columns.Add("Key", keyColumn);
            keyColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(keyColumn);
            var originalFilenameColumn = new Column("OriginalFilename", "TEXT", uploadsTable);
            uploadsTable.Columns.Add("OriginalFilename", originalFilenameColumn);
            originalFilenameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(originalFilenameColumn);
            var remoteIpAddressColumn = new Column("RemoteIpAddress", "TEXT", uploadsTable)
            {
                IsNullable = true
            };
            uploadsTable.Columns.Add("RemoteIpAddress", remoteIpAddressColumn);
            remoteIpAddressColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(remoteIpAddressColumn);
            var sizeColumn = new Column("Size", "INTEGER", uploadsTable);
            uploadsTable.Columns.Add("Size", sizeColumn);
            sizeColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<long>(sizeColumn);
            var uploadTimeColumn = new Column("UploadTime", "TEXT", uploadsTable);
            uploadsTable.Columns.Add("UploadTime", uploadTimeColumn);
            uploadTimeColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTime>(uploadTimeColumn);
            var userAgentColumn = new Column("UserAgent", "TEXT", uploadsTable)
            {
                IsNullable = true
            };
            uploadsTable.Columns.Add("UserAgent", userAgentColumn);
            userAgentColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(userAgentColumn);
            relationalModel.Tables.Add(("Uploads", null), uploadsTable);
            var uploadsTableMapping = new TableMapping(upload, uploadsTable, null);
            uploadsTable.AddTypeMapping(uploadsTableMapping, false);
            tableMappings.Add(uploadsTableMapping);
            RelationalModel.CreateColumnMapping(idColumn, upload.FindProperty("Id")!, uploadsTableMapping);
            RelationalModel.CreateColumnMapping(checksumMd5Column, upload.FindProperty("ChecksumMd5")!, uploadsTableMapping);
            RelationalModel.CreateColumnMapping(contentTypeColumn, upload.FindProperty("ContentType")!, uploadsTableMapping);
            RelationalModel.CreateColumnMapping(extensionColumn, upload.FindProperty("Extension")!, uploadsTableMapping);
            RelationalModel.CreateColumnMapping(fileIdColumn, upload.FindProperty("FileId")!, uploadsTableMapping);
            RelationalModel.CreateColumnMapping(isDeletedColumn, upload.FindProperty("IsDeleted")!, uploadsTableMapping);
            RelationalModel.CreateColumnMapping(keyColumn, upload.FindProperty("Key")!, uploadsTableMapping);
            RelationalModel.CreateColumnMapping(originalFilenameColumn, upload.FindProperty("OriginalFilename")!, uploadsTableMapping);
            RelationalModel.CreateColumnMapping(remoteIpAddressColumn, upload.FindProperty("RemoteIpAddress")!, uploadsTableMapping);
            RelationalModel.CreateColumnMapping(sizeColumn, upload.FindProperty("Size")!, uploadsTableMapping);
            RelationalModel.CreateColumnMapping(uploadTimeColumn, upload.FindProperty("UploadTime")!, uploadsTableMapping);
            RelationalModel.CreateColumnMapping(userAgentColumn, upload.FindProperty("UserAgent")!, uploadsTableMapping);
            var pK_Uploads = new UniqueConstraint("PK_Uploads", uploadsTable, new[] { idColumn });
            uploadsTable.PrimaryKey = pK_Uploads;
            pK_Uploads.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<long>(pK_Uploads));
            var pK_UploadsKey = RelationalModel.GetKey(this,
                "Uploader.Core.Entities.Upload",
                new[] { "Id" });
            pK_Uploads.MappedKeys.Add(pK_UploadsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_UploadsKey).Add(pK_Uploads);
            uploadsTable.UniqueConstraints.Add("PK_Uploads", pK_Uploads);
            return relationalModel.MakeReadOnly();
        }
    }
}
