// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using Uploader.Core.Entities;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Uploader.Infrastructure.Data.Models
{
    public static class UploadUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref long Id(Upload @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ChecksumMd5>k__BackingField")]
        public static extern ref string ChecksumMd5(Upload @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<ContentType>k__BackingField")]
        public static extern ref string ContentType(Upload @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Extension>k__BackingField")]
        public static extern ref string Extension(Upload @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<FileId>k__BackingField")]
        public static extern ref string FileId(Upload @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IsDeleted>k__BackingField")]
        public static extern ref bool IsDeleted(Upload @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Key>k__BackingField")]
        public static extern ref string Key(Upload @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<OriginalFilename>k__BackingField")]
        public static extern ref string OriginalFilename(Upload @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<RemoteIpAddress>k__BackingField")]
        public static extern ref string RemoteIpAddress(Upload @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Size>k__BackingField")]
        public static extern ref long Size(Upload @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UploadTime>k__BackingField")]
        public static extern ref DateTime UploadTime(Upload @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<UserAgent>k__BackingField")]
        public static extern ref string UserAgent(Upload @this);
    }
}
